### ISSUE TITLE
react: Uncaught TypeError: e.git is undefined

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/common#1871]
From https://github.com/cucumber/cucumber-jvm/issues/2464 given this meta message:

```
{
  "meta": {
    "protocolVersion": "17.1.1",
    "implementation": {
      "name": "cucumber-jvm",
      "version": "7.2.2"
    },
    "runtime": {
      "name": "OpenJDK 64-Bit Server VM",
      "version": "11.0.2+9"
    },
    "os": {
      "name": "Linux"
    },
    "cpu": {
      "name": "amd64"
    },
    "ci": {
      "name": "Jenkins",
      "url": "https://example.com",
      "buildNumber": "6"
    }
  }
}
```

The html report will fail to render with:

```
Uncaught TypeError: e.git is undefined
    CICommitLink file:///home/mpkorstanje/Downloads/HTML_20Report_206/index.html:34
    ni file:///home/mpkorstanje/Downloads/HTML_20Report_206/index.html:34
    Uo file:///home/mpkorstanje/Downloads/HTML_20Report_206/index.html:34
    bl file:///home/mpkorstanje/Downloads/HTML_20Report_206/index.html:34
    zl file:///home/mpkorstanje/Downloads/HTML_20Report_206/index.html:34
    El file:///home/mpkorstanje/Downloads/HTML_20Report_206/index.html:34
    pl file:///home/mpkorstanje/Downloads/HTML_20Report_206/index.html:34
    ll file:///home/mpkorstanje/Downloads/HTML_20Report_206/index.html:34
    Ql file:///home/mpkorstanje/Downloads/HTML_20Report_206/index.html:34
    es file:///home/mpkorstanje/Downloads/HTML_20Report_206/index.html:34
    ml file:///home/mpkorstanje/Downloads/HTML_20Report_206/index.html:34
    es file:///home/mpkorstanje/Downloads/HTML_20Report_206/index.html:34
    render file:///home/mpkorstanje/Downloads/HTML_20Report_206/index.html:34
    9963 file:///home/mpkorstanje/Downloads/HTML_20Report_206/index.html:34
    n file:///home/mpkorstanje/Downloads/HTML_20Report_206/index.html:34
    <anonymous> file:///home/mpkorstanje/Downloads/HTML_20Report_206/index.html:34
    <anonymous> file:///home/mpkorstanje/Downloads/HTML_20Report_206/index.html:34
```

Because the `CICommitLink` assumes `git` is never undefined.

https://github.com/cucumber/common/blob/0fd7c42c53420566a6b5e3bfc42565cf3457443b/react/javascript/src/components/app/CICommitLink.tsx#L24

However the message specification allows it to be undefined:

https://github.com/cucumber/common/blob/0fd7c42c53420566a6b5e3bfc42565cf3457443b/messages/jsonschema/Meta.json#L6-L11

**Comment by aslakhellesoy** [comment]
@davidjgoss we have to update the code to anticipate `ci.git` being undefined. I believe I fixed this in https://github.com/cucumber/cucumber-react/commit/0445c6ef0165a2877af6de07e1f0334a5de53fe6#diff-3cf19d71bb3e6f73142532ec673421a65dba96ef99e21e777315dc4a70ccb5c6 - thanks to the stricter null-checking that I enabled after we moved Cucumber-React to a new repo.

So the question is - do we release a patch release from this repo (the code is still there), or do we push through with https://github.com/cucumber/cucumber-react/pull/11 so we can release from the new repo? How far off are we from making the new Cucumber-React releaseable?

**Comment by davidjgoss** [comment]
@aslakhellesoy still a couple of issues over on that PR:

- 3 failing tests around search functionality
- CI step for test hanging

I think if it's not too painful might be best to get a fix out from the monorepo today.

**Comment by aslakhellesoy** [comment]
Ok makes sense. I'll try to get that done tonight or tomorrow.

**Comment by aurelien-reeves** [comment]
What is the status of this issue?
Is it fixed?

The ESM thing will not be ready soon so if nothing else is in progress, we may release it?

**Comment by davidjgoss** [comment]
@aurelien-reeves agreed, 🚀

**Comment by aurelien-reeves** [comment]
@aslakhellesoy Should we release a RC as this will be a new major version?
I assume the releasing guide suggest to release RC with final cucumbers, not internals!?

**Comment by aslakhellesoy** [comment]
As described in [RELEASING.md](https://github.com/cucumber/.github/blob/main/RELEASING.md#major-release):

> If you are releasing cucumber-{jvm,js,ruby} and bumping the MAJOR version, make a -rc.N release candidate. The release candidate should be available for at least a month to give users time to validate that there are no unexpected breaking changes.

I'll update the text to explicitly state that no RC is needed for libraries, to remove any doubt.

**Comment by aslakhellesoy** [comment]
Updated: https://github.com/cucumber/.github/commit/e78ca1dd66d327aa1a7d3b010d8ddc2a9866ba2f

**Comment by aurelien-reeves** [comment]
Thanks.
I actually did that update myself: https://github.com/cucumber/.github/commit/83d26377ae7ce561d9efee6d3b50a75ea38ceb69
As I knew how to process to release a new RC version, I did even not scroll down to that section 😓

**Comment by aurelien-reeves** [comment]
It should be fixed as part of html-formatter@18.0.0

**Comment by mpkorstanje** [comment]
It doesn't break any more but, some information is still missing:

With this meta message:

```
{
  "meta": {
    "protocolVersion": "17.1.1",
    "implementation": {
      "name": "cucumber-jvm",
      "version": "${parent.version}"
    },
    "runtime": {
      "name": "OpenJDK 64-Bit Server VM",
      "version": "15.0.2+7"
    },
    "os": {
      "name": "Linux"
    },
    "cpu": {
      "name": "amd64"
    },
    "ci": {
      "name": "GitLab",
      "url": "https://gitlab.com/gitlab-examples/ci-debug-trace/-/jobs/379424655",
      "buildNumber": "12345"
    }
  }
}
```

I would expect to see the url to the job.

![image](https://user-images.githubusercontent.com/6946919/151701640-f7aed59a-21a2-4ab3-8f7d-8f4f13dab58b.png)

**Comment by aurelien-reeves** [comment]
I've reported the issue here: https://github.com/cucumber/cucumber-react/issues/50

@mpkorstanje agree to close this one?
